# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Voyanti EMS Addon
version: "1.2.8"
slug: voyanti_ems
description: Voyanti Energy Management System Addon
url: "https://github.com/heinrich321/voyanti-ems/tree/main"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  VOYANTI_SITE_ID: "xxxxxxxxxxxxx"
  MQTT_HOST: core-mosquitto
  MQTT_PORT: 1883
  MQTT_USERNAME: hass
  MQTT_PASSWORD: ""
schema:
  VOYANTI_SITE_ID: str
  MQTT_HOST: str
  MQTT_PORT: port
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
image: "ghcr.io/heinrich321/{arch}-voyanti-ems"
