# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Voyanti EMS Addon
version: "1.2.2"
slug: voyanti_ems
description: Voyanti Energy Management System Addon
url: "https://github.com/heinrich321/voyanti-ems/tree/main"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world.. VY!"
  mqtt:
    - host: 127.0.0.1
      port: 1883
      client_id: "mqtt"
      username: "mqtt"
      password: ""
schema:
  message: "str?"
image: "ghcr.io/heinrich321/{arch}-voyanti-ems"
