# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Voyanti EMS Addon
version: "1.2.1"
slug: voyanti_ems
description: Voyanti Energy Management System Addon
url: "https://github.com/heinrich321/voyanti-ems/tree/main"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world.. VY!"
schema:
  message: "str?"
image: "ghcr.io/heinrich321/{arch}-voyanti-ems"
